# Format: RequestClass=ResponseClass:field_request_1=field_response_1,field_request_2=field_response_2
[DEFAULT]
CreateUserRequest=CreateUserResponse:username=username,role=role
DepositRequest=AccountResponse:id=id
AccountResponse=AccountResponse:id=id,balance=balance,transactions=transactions
TransferRequest=TransferResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
ProfileUpdateRequest=CustomerProfileResponse:name=name